matrix:
  include:
    - go: 1.10.x
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - mysql-5.7-trusty
          packages:
            - mysql-server
            - mysql-client
language: go
before_script:
    - mysql --version
script:
    - go test -v -race ./...
