matrix:
  include:
    - dist: trusty
      sudo: required
      addons:
      apt:
        sources:
          - mysql-5.7-trusty
        packages:
          - mysql-server
          - mysql-client
language: go
before_script:
    - mysql --version
go:
    - 1.9.x
    - 1.10.x
    - tip
script:
    - go test -v -race ./...
